-
  version: 1.21.{build}
  platform: Any CPU
  configuration: Release
  branches:
    only:
      - release
  build:
    publish_nuget: false
  before_build:
  - cmd: nuget restore Essentials\Essentials.sln
    
  - path: '**/Essentials.zip'
    name: Plugin
