//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Essentials.Resources {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Essentials.Resources.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Essentials plugin was on enabled.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Essential_PluginOnEnabled {
            get {
                return ResourceManager.GetString("Essential_PluginOnEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set own game mode to {{value}}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Gamemode_DisplayCompletedResult {
            get {
                return ResourceManager.GetString("Gamemode_DisplayCompletedResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set {{target}}&apos;s game mode to {{gamemode}}.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Gamemode_DisplayCompletedResult_Target {
            get {
                return ResourceManager.GetString("Gamemode_DisplayCompletedResult_Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sets a player&apos;s game mode.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Gamemode_Help1 {
            get {
                return ResourceManager.GetString("Gamemode_Help1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sets a target&apos;s game mode.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Gamemode_Help2 {
            get {
                return ResourceManager.GetString("Gamemode_Help2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {{value}} is not game mode value.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Gamemode_InvaildGameModeValue {
            get {
                return ResourceManager.GetString("Gamemode_InvaildGameModeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No targets metched search.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Gamemode_PlayerNotFound {
            get {
                return ResourceManager.GetString("Gamemode_PlayerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {{target}} has kicked.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Kick_CompleteMessage {
            get {
                return ResourceManager.GetString("Kick_CompleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You are kicked과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Kick_DisconnectMessage {
            get {
                return ResourceManager.GetString("Kick_DisconnectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {{killer}} has killed you with commands.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Kill_DisplayMessage {
            get {
                return ResourceManager.GetString("Kill_DisplayMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No targets metched search.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Tp_NoMatch {
            get {
                return ResourceManager.GetString("Tp_NoMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sent teleport request to {{target}}.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Tp_S1 {
            get {
                return ResourceManager.GetString("Tp_S1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   has teleported to {{target}}&apos;s location.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Tp_SenderMsg1 {
            get {
                return ResourceManager.GetString("Tp_SenderMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   has teleported you to {{target}}&apos;s location.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Tp_TargetMsg1 {
            get {
                return ResourceManager.GetString("Tp_TargetMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   has teleported {{target}} to your location.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Tp_TargetMsg2 {
            get {
                return ResourceManager.GetString("Tp_TargetMsg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   has teleported to {{xyz}}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Tp_XYZMsg {
            get {
                return ResourceManager.GetString("Tp_XYZMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   has teleported you to {{xyz}}.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Tp_XYZMsg2 {
            get {
                return ResourceManager.GetString("Tp_XYZMsg2", resourceCulture);
            }
        }
    }
}
