//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Essentials.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Essentials.Resources.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are banned..
        /// </summary>
        public static string Ban_DisconnectMsg {
            get {
                return ResourceManager.GetString("Ban_DisconnectMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{target}} has banned..
        /// </summary>
        public static string Ban_SendMsg {
            get {
                return ResourceManager.GetString("Ban_SendMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Essentials plugin was on enabled..
        /// </summary>
        public static string Essential_PluginOnEnabled {
            get {
                return ResourceManager.GetString("Essential_PluginOnEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permission to access the command..
        /// </summary>
        public static string Essentials_NoMatchPermission {
            get {
                return ResourceManager.GetString("Essentials_NoMatchPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set own game mode to {{value}}.
        /// </summary>
        public static string Gamemode_DisplayCompletedResult {
            get {
                return ResourceManager.GetString("Gamemode_DisplayCompletedResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set {{target}}&apos;s game mode to {{gamemode}}..
        /// </summary>
        public static string Gamemode_DisplayCompletedResult_Target {
            get {
                return ResourceManager.GetString("Gamemode_DisplayCompletedResult_Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets a player&apos;s game mode..
        /// </summary>
        public static string Gamemode_Help1 {
            get {
                return ResourceManager.GetString("Gamemode_Help1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets a target&apos;s game mode..
        /// </summary>
        public static string Gamemode_Help2 {
            get {
                return ResourceManager.GetString("Gamemode_Help2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{value}} is not game mode value..
        /// </summary>
        public static string Gamemode_InvaildGameModeValue {
            get {
                return ResourceManager.GetString("Gamemode_InvaildGameModeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No targets metched search..
        /// </summary>
        public static string Gamemode_PlayerNotFound {
            get {
                return ResourceManager.GetString("Gamemode_PlayerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Healed {{target}}.
        /// </summary>
        public static string Heal_1 {
            get {
                return ResourceManager.GetString("Heal_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{sender}} healed you.
        /// </summary>
        public static string Heal_2 {
            get {
                return ResourceManager.GetString("Heal_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{target}} has kicked..
        /// </summary>
        public static string Kick_CompleteMessage {
            get {
                return ResourceManager.GetString("Kick_CompleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are kicked.
        /// </summary>
        public static string Kick_DisconnectMessage {
            get {
                return ResourceManager.GetString("Kick_DisconnectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{killer}} has killed you with commands..
        /// </summary>
        public static string Kill_DisplayMessage {
            get {
                return ResourceManager.GetString("Kill_DisplayMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted the teleport request..
        /// </summary>
        public static string Tp_A1 {
            get {
                return ResourceManager.GetString("Tp_A1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teleport request is accepted by {{sender}}..
        /// </summary>
        public static string Tp_A2 {
            get {
                return ResourceManager.GetString("Tp_A2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declined the teleport request..
        /// </summary>
        public static string Tp_D1 {
            get {
                return ResourceManager.GetString("Tp_D1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teleport request is declined by {{sender}}..
        /// </summary>
        public static string Tp_D2 {
            get {
                return ResourceManager.GetString("Tp_D2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No targets metched search..
        /// </summary>
        public static string Tp_NoMatch {
            get {
                return ResourceManager.GetString("Tp_NoMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There isn&apos;t refering teleport request..
        /// </summary>
        public static string Tp_P {
            get {
                return ResourceManager.GetString("Tp_P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent teleport request to {{target}}..
        /// </summary>
        public static string Tp_S1 {
            get {
                return ResourceManager.GetString("Tp_S1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has teleported to {{target}}&apos;s location..
        /// </summary>
        public static string Tp_SenderMsg1 {
            get {
                return ResourceManager.GetString("Tp_SenderMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{sender}} sent teleport request to you..
        /// </summary>
        public static string Tp_T1 {
            get {
                return ResourceManager.GetString("Tp_T1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to accpet {{color}}tpaccept,.
        /// </summary>
        public static string Tp_T2 {
            get {
                return ResourceManager.GetString("Tp_T2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to decline {{color}}tpdeny.
        /// </summary>
        public static string Tp_T3 {
            get {
                return ResourceManager.GetString("Tp_T3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enter the command..
        /// </summary>
        public static string Tp_T4 {
            get {
                return ResourceManager.GetString("Tp_T4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has teleported you to {{target}}&apos;s location..
        /// </summary>
        public static string Tp_TargetMsg1 {
            get {
                return ResourceManager.GetString("Tp_TargetMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has teleported {{target}} to your location..
        /// </summary>
        public static string Tp_TargetMsg2 {
            get {
                return ResourceManager.GetString("Tp_TargetMsg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has teleported to {{xyz}}.
        /// </summary>
        public static string Tp_XYZMsg {
            get {
                return ResourceManager.GetString("Tp_XYZMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has teleported you to {{xyz}}..
        /// </summary>
        public static string Tp_XYZMsg2 {
            get {
                return ResourceManager.GetString("Tp_XYZMsg2", resourceCulture);
            }
        }
    }
}
